config/routes.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  default_url_options Settings.default_url_options.symbolize_keys

  mount Sidekiq::Web => '/sidekiq'
  root to: 'dashboard#index'
  resources :reports
  resources :withdraws
  resources :deposits
  resources :transactions
  resources :accounts
  resources :trades
  resources :markets
  resources :orders
  resources :members
  resources :adjustments
  resources :internal_transfers
  resources :transfers
  resources :whaler_transfers
  resources :member_transfers
  resources :service_withdraws, only: %i[index show]
  resources :service_invoices, only: %i[index show]
  resources :service_transactions, only: %i[index show]
  resources :wallets, only: %i[index show]
  resources :bitzlato_wallets, only: %i[index show]
  resources :payment_addresses, only: %i[index show]
  resources :currencies, only: %i[index show]
  resources :blockchains, only: %i[index show]
  resources :block_numbers, only: %i[index show]
  namespace :operations do
    resources :liabilities
    resources :accounts
    resources :assets
    resources :expenses
    resources :revenues
  end
end

app/models/account.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

class Account < PeatioRecord
  extend Memoist

  self.primary_keys = :currency_id, :member_id

  belongs_to :currency, required: true
  belongs_to :member, required: true

  scope :visible, -> { joins(:currency).merge(Currency.where(visible: true)) }
  scope :ordered, -> { joins(:currency).order(position: :asc) }

  def divergence
    estimated_amount - amount
  end

  def trades
    member.trades.where(market_id: currency.dependent_markets.pluck(:symbol))
  end

  def sell_trades
    Trade.where(market_id: currency.dependent_markets.pluck(:symbol)).where('((taker_type = ? and taker_id = ?) or (taker_type=? and maker_id=?))', 'sell',
                                                                            member_id, 'buy', member_id)
  end

  def buy_trades
    Trade.where(market_id: currency.dependent_markets.pluck(:symbol)).where('((taker_type = ? and taker_id = ?) or (taker_type=? and maker_id=?))', 'buy',
                                                                            member_id, 'sell', member_id)
  end

  def total_paid
    buy_trades.where(market_id: currency.quote_markets.pluck(:symbol)).sum(:total)
  end

  def total_revenue
    sell_trades.where(market_id: currency.quote_markets.pluck(:symbol)).sum(:total)
  end

  def total_sell
    sell_trades.where(market_id: currency.base_markets.pluck(:symbol)).sum(:amount)
  end

  def total_buy
    buy_trades.where(market_id: currency.base_markets.pluck(:symbol)).sum(:amount)
  end

  def withdraws
    member.withdraws.where(currency_id: currency_id)
  end

  def deposits
    member.deposits.where(currency_id: currency_id)
  end

  def locked_in_withdraws
    member.withdraws.where(currency_id: currency_id, is_locked: true).sum(:sum)
  end

  def locked_in_deposits
    member.deposits.where(currency_id: currency_id, is_locked: true).sum(:amount)
  end

  def base_orders
    member.orders.where(market_id: Market.where(base_unit: currency_id).pluck(:symbol))
  end

  def bid_orders
    quote_orders.where(type: 'OrderBid')
  end

  def ask_orders
    base_orders.where(type: 'OrderAsk')
  end

  def quote_orders
    member.orders.where(market_id: Market.where(quote_unit: currency_id).pluck(:symbol))
  end

  def amount
    balance + locked
  end

  def trade_income
    total_buy - total_sell + total_revenue - total_paid
  end

  def total_deposit_amount
    deposits.success.where(currency_id: currency_id).sum(:amount)
  end
  memoize :total_deposit_amount

  def total_withdraw_amount
    withdraws.success.where(currency_id: currency_id).sum(:amount)
  end
  memoize :total_withdraw_amount

  def operations_revenues
    member.operations_revenues.where(currency_id: currency_id)
  end

  def trades_fee
    operations_revenues.sum(:credit)
  end

  def estimated_amount
    total_deposit_amount - total_withdraw_amount + trade_income - trades_fee
  end
end

app/models/operation.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

# {Operation} provides generic methods for the accounting operations
# models.
# @abstract
class Operation < PeatioRecord
  belongs_to :reference, polymorphic: true
  belongs_to :currency, foreign_key: :currency_id
  belongs_to :account, class_name: 'Operations::Account',
                       foreign_key: :code, primary_key: :code

  self.abstract_class = true

  # Returns operation amount with sign.
  def amount
    credit.zero? ? -debit : credit
  end

  class << self
    def operation_type
      name.demodulize.downcase
    end

    def balance(currency: nil, created_at_from: nil, created_at_to: nil)
      if currency.blank?
        db_balances = all
        db_balances = db_balances.where('created_at > ?', created_at_from) if created_at_from.present?
        db_balances = db_balances.where('created_at < ?', created_at_to) if created_at_to.present?
        db_balances = db_balances.group(:currency_id)
                                 .sum('credit - debit')

        Currency.ids.map(&:to_sym).each_with_object({}) do |id, memo|
          memo[id] = db_balances[id.to_s] || 0
        end
      else
        where(currency: currency).sum('credit - debit')
      end
    end
  end
end

app/models/operations/account.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

# TODO: Add admin rubric for Account.
module Operations
  class Account < PeatioRecord
    SCOPES = %w[member platform].freeze

    MEMBER_TYPES = %w[liability].freeze
    PLATFORM_TYPES = %w[asset expense revenue].freeze
    TYPES = (MEMBER_TYPES + PLATFORM_TYPES).freeze

    has_many :assets, foreign_key: :code, primary_key: :code
    has_many :expenses, foreign_key: :code, primary_key: :code
    has_many :revenues, foreign_key: :code, primary_key: :code
    has_many :liabilities, foreign_key: :code, primary_key: :code

    def self.table_name_prefix
      'operations_'
    end

    # Type column reserved for STI.
    self.inheritance_column = nil

    # Allows dynamically check scopes.
    #   scope.platform?
    def scope
      super&.inquiry
    end

    # Allows dynamically check kinds.
    #   kind.main?
    def kind
      super&.inquiry
    end

    def to_s
      description + ' [' + scope + ']'
    end

    def records_class
      ('Operations::' + records_name.singularize.camelcase).constantize
    end

    def records_name
      type.pluralize
    end

    def records
      send records_name
    end
  end
end

app/models/operations/asset.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  # {Asset} is a balance sheet operation
  class Asset < Operation
    scope :exclude_bots, ->(exclude = true) do
      if exclude
        bots_ids = [Member::DEEP_STONER_BOT_ID, Member::BARGAINER_BOT_ID]
        bots_uids = Member.where(id: bots_ids).pluck(:uid)

        joins(%Q{
          LEFT JOIN deposits ON deposits.id = assets.reference_id AND assets.reference_type = 'Deposit'
          LEFT JOIN withdraws ON withdraws.id = assets.reference_id AND assets.reference_type = 'Withdraw'
          LEFT JOIN member_transfers ON member_transfers.id = assets.reference_id AND assets.reference_type = 'MemberTransfer'
          LEFT JOIN adjustments ON adjustments.id = assets.reference_id AND assets.reference_type = 'Adjustment'
        })
          .where(%Q{
            (reference_type = 'Deposit' AND deposits.member_id NOT IN (:bots_ids)) OR
            (reference_type = 'Withdraw' AND withdraws.member_id NOT IN (:bots_ids)) OR
            (reference_type = 'MemberTransfer' AND member_transfers.member_id NOT IN (:bots_ids)) OR
            (reference_type = 'Adjustment' AND adjustments.receiving_account_number !~* :bots_uids)
            }, bots_ids: bots_ids, bots_uids: "(#{bots_uids.join('|')})")
      end
    end

    def self.ransackable_scopes(auth_object = nil)
      [:exclude_bots]
    end
  end
end

app/models/operations/expense.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  # {Expense} is a income statement operation
  class Expense < Operation
    scope :exclude_bots, ->(exclude = true) do
      if exclude
        bots_ids = [Member::DEEP_STONER_BOT_ID, Member::BARGAINER_BOT_ID]
        bots_uids = Member.where(id: bots_ids).pluck(:uid)

        joins(%Q{
          LEFT JOIN deposits ON deposits.id = expenses.reference_id AND expenses.reference_type = 'Deposit'
          LEFT JOIN withdraws ON withdraws.id = expenses.reference_id AND expenses.reference_type = 'Withdraw'
          LEFT JOIN member_transfers ON member_transfers.id = expenses.reference_id AND expenses.reference_type = 'MemberTransfer'
          LEFT JOIN adjustments ON adjustments.id = expenses.reference_id AND expenses.reference_type = 'Adjustment'
        })
          .where(%Q{
            (reference_type = 'Deposit' AND deposits.member_id NOT IN (:bots_ids)) OR
            (reference_type = 'Withdraw' AND withdraws.member_id NOT IN (:bots_ids)) OR
            (reference_type = 'MemberTransfer' AND member_transfers.member_id NOT IN (:bots_ids)) OR
            (reference_type = 'Adjustment' AND adjustments.receiving_account_number !~* :bots_uids)
            }, bots_ids: bots_ids, bots_uids: "(#{bots_uids.join('|')})")
      end
    end
  end
end

app/models/operations/liability.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  # {Liability} is a balance sheet operation
  class Liability < Operation
    belongs_to :member

    scope :exclude_bots, ->(exclude = true) do
      where.not(member_id: [Member::DEEP_STONER_BOT_ID, Member::BARGAINER_BOT_ID]) if exclude
    end

    def self.ransackable_scopes(auth_object = nil)
      [:exclude_bots]
    end
  end
end

app/models/operations/revenue.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  # {Revenue} is a income statement operation
  class Revenue < Operation
    belongs_to :member
    belongs_to :trade, foreign_key: :reference_id

    scope :exclude_bots, ->(exclude = true) do
      where.not(member_id: [Member::DEEP_STONER_BOT_ID, Member::BARGAINER_BOT_ID]) if exclude
    end

    scope :accountable, -> { where.not(reference_type: 'Adjustment') }

    def self.ransackable_scopes(auth_object = nil)
      [:exclude_bots]
    end
  end
end

app/controllers/accounts_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

class AccountsController < ResourcesController
  include CurrencySupport

  layout 'fluid'

  def show
    render locals: { account: Account.find(params[:id]) }
  end

  private

  def index_form
    'accounts_form'
  end
end

app/controllers/operations/accounts_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  class AccountsController < ResourcesController
    include CurrencySupport

    layout 'fluid'

    helper_method :form

    def show
      render locals: { record: Operations::Account.find(params[:id]) }
    end

    def index
      render locals: { accounts: accounts }
    end

    private

    def accounts
      Operations::Account.order(:code)
    end

    def form
      @form ||= OperationAccountsForm.new(params[:operation_accounts_form]&.permit! || {})
    end
  end
end

app/controllers/operations/application_controller.rb
# frozen_string_literal: true

# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

module Operations
  class ApplicationController < ::ApplicationController
    include CurrencySupport

    helper_method :account

    private

    def account
      account_id = params.dig(:q, :account_id_eq)
      return if account_id.nil?

      Operations::Account.find account_id
    end
  end
end

app/controllers/operations/assets_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  class AssetsController < ResourcesController
    include CurrencySupport

    def show
      render locals: { record: Operations::Asset.find(params[:id]) }
    end

    private

    def index_form
      'operation_form'
    end

  end
end

app/controllers/operations/liabilities_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  class LiabilitiesController < ResourcesController
    include CurrencySupport
    layout 'fluid'

    private

    def index_form
      'operation_form'
    end
  end
end

app/controllers/operations/revenues_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module Operations
  class RevenuesController < ResourcesController
    include CurrencySupport
    include RansackSupport

    layout 'fluid'

    # def index
    # render locals: {
    # revenues: paginate(revenues),
    # member: member,
    # totals: {
    # debit: revenues.sum(:debit),
    # credit: revenues.sum(:credit),
    # }
    # }
    # end

    def show
      render locals: { record: Operations::Revenue.find(params[:id]) }
    end

    private

    def index_form
      'operation_form'
    end
  end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

module AccountsHelper
  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity
  def account_table_head_column(column, currency, totals)
    content_tag :td, class: AccountDecorator.table_th_class(column) do
      case column.to_s
      when 'id'
        t('total')
      when 'total_deposit_amount'
        format_money(currency.total_completed_deposits, currency)
      when 'total_withdraw_amount'
        format_money(currency.total_completed_withdraws, currency)
      when 'estimated_amount'
        format_money(currency.estimated_amount, currency)
      when 'divergence'
        format_divergence(currency.estimated_amount - (totals[:total_balance] + totals[:total_locked]), currency)
      when 'amount'
        format_money(totals[:total_balance] + totals[:total_locked], currency)
      when 'balance'
        format_money(totals[:total_balance], currency)
      when 'locked'
        format_money(totals[:total_locked], currency)
      else
        if totals.key? column.to_sym
          format_money totals[column.to_sym], currency
        else
          middot
        end
      end
    end
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity
end

app/helpers/operations_helper.rb
# frozen_string_literal: true

# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

module OperationsHelper
  def check_operations_amount(account)
    # TODO
  end
end

app/views/operations/accounts/_system.slim
- bw =  BitzlatoWallet.market_balances.transform_values { |v| { p2p: v } }
- w = AddressBalancesQuery.new.peatio_wallet_balances.transform_values { |v| { market: v } }
- pa = AddressBalancesQuery.new.deposit_balances.transform_values { |v| {payment_address: v} }
- balances = bw.deep_merge(w).deep_merge(pa)

thead.thead-dark
  tr
    th System balance
    th

    - Currency.order(:id).visible.each do |currency|
      th.text-right= format_currency currency

tbody
  tr
    th.text-right colspan=2 Total
    - Currency.order(:id).visible.each do |currency|
      td.text-right width=200
        - balance = balances.dig(currency.cc_code.to_s.downcase, :p2p).to_d + balances.dig(currency.id, :market).to_d + balances.dig(currency.id, :payment_address).to_d
        - if balance.zero?
          = middot
        - else
          = format_money(balance, currency)

  tr
    th.text-right colspan=2 P2P
    - Currency.order(:id).visible.each do |currency|
      td.text-right width=200
        - balance = balances.dig(currency.cc_code.to_s.downcase, :p2p)
        - if balance.nil?
          = middot
        - else
          = link_to format_money(balance, currency), bitzlato_wallets_path

  tr
    th.text-right colspan=2 Market
    - Currency.order(:id).visible.each do |currency|
      td.text-right width=200
        - balance = balances.dig(currency.id, :market)
        - if balance.nil?
          = middot
        - else
          = link_to format_money(balance, currency), wallets_path

  tr
    th.text-right colspan=2 Deposit Accounts
    - Currency.order(:id).visible.each do |currency|
      td.text-right width=200
        - balance = balances.dig(currency.id, :payment_address)
        - if balance.nil?
          = middot
        - else
          = link_to format_money(balance, currency), payment_addresses_path(q: { currency_id_eq: currency.id, with_balances: true })

app/views/operations/accounts/_table.slim
thead.thead-dark
  tr
    th= description
    th

    - Currency.order(:id).visible.each do |currency|
      th.text-right= format_currency currency

tbody
  - Operations::AccountDecorator.decorate(accounts.order(:currency_type, :scope)).each do |account|
    - records = account.records
    - records = records.exclude_bots if form.exclude_bots

    - go = grouped_operations(records)
    - [:balance, :credit, :debit].each do |d|
      tr
        - if d==:balance
          th rowspan=3
            div= account.description
            .text-muted.text-small= '#' + account.code.to_s
        th.text-right class=(d==:balance ? '' : 'text-small')
          = t d
        - Currency.order(:id).visible.each do |currency|
          - data = go[currency.id]
          td.text-right class=(d==:balance ? '' : 'text-small') width=200
            - if data.nil?
              = middot
            - else
              - par = d == :balance ? {} : { d.to_s+"_gt" => 0}
              = link_to url_for([:operations, account.records_name.to_sym, q: par.merge( account_id_eq: account.id, currency_id_eq: currency.id )]) do
                = format_money data[d], currency
            = check_operations_amount(account)

app/views/operations/accounts/index.slim
.py-3= back_link
h1= accounts.model_name.human_plural
hr

= simple_form_for form, url: operations_accounts_path, method: :get do |f|
  .row
    .col-md-3
      = f.input :exclude_bots, as: :boolean, checked_value: true, unchecked_value: false

    .col-md-2
      = f.button :submit, 'Поиск', class: 'btn btn-primary'

.mt-3

table.table.table-striped.table-hover.table-narrow.table-bordered
  = render 'system'

  - [:coin, :fiat].each do |currency_type|
    - [:platform, :member].each do |scope|
      = render 'table', accounts: accounts.where(currency_type: currency_type, scope: scope), description: [currency_type, scope].join(': ')