config/routes.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  default_url_options Settings.default_url_options.symbolize_keys

  mount Sidekiq::Web => '/sidekiq'
  root to: 'dashboard#index'
  resources :reports
  resources :withdraws
  resources :deposits
  resources :transactions
  resources :accounts
  resources :trades
  resources :markets
  resources :orders
  resources :members
  resources :adjustments
  resources :internal_transfers
  resources :transfers
  resources :whaler_transfers
  resources :member_transfers
  resources :service_withdraws, only: %i[index show]
  resources :service_invoices, only: %i[index show]
  resources :service_transactions, only: %i[index show]
  resources :wallets, only: %i[index show]
  resources :bitzlato_wallets, only: %i[index show]
  resources :payment_addresses, only: %i[index show]
  resources :currencies, only: %i[index show]
  resources :blockchains, only: %i[index show]
  resources :block_numbers, only: %i[index show]
  namespace :operations do
    resources :liabilities
    resources :accounts
    resources :assets
    resources :expenses
    resources :revenues
  end
end

app/models/report.rb
# frozen_string_literal: true

# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

class Report < ReportsRecord
  extend Enumerize

  belongs_to :author, class_name: 'Member'
  belongs_to :member, optional: true

  mount_uploader :file, ReportFileUploader

  STATES = %(pending processing failed success)
  enumerize :state, in: STATES

  before_create do
    self.form ||= {}
  end

  before_save do
    self.member_id = form_object.try(:member_id)
  end

  after_commit :perform_async, on: :create

  def self.form_class
    TimeRangeForm
  end

  def results
    ActiveSupport::HashWithIndifferentAccess.new super
  end

  def records_count
    results[:records_count]
  rescue StandardError => e
    report_exception(e, context: { report_id: id })
    e
  end

  def form_object
    self.class.form_class.try :new, form.symbolize_keys
  end

  def perform_async
    ReporterWorker.perform_async id
  end

  def perform!
    with_lock do
      update status: :processing
      update results: reporter.perform, file: reporter.file, status: :success, processed_at: Time.zone.now, error_message: nil
    rescue StandardError => e
      report_exception(e, context: { report_id: id })
      update status: :failed, error_message: [e.class.to_s, e.message].join('->')
    end
  end

  def name
    self.class.model_name.human
  end

  def reporter_class
    [self.class.name, 'Generator'].join('::').constantize
  end

  def reporter
    @reporter ||= reporter_class.new(form_object, [self.class.name, id].join('-'))
  end
end

app/controllers/reports_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

require 'active_storage/blob'
require 'active_storage/blob/analyzable'
class ReportsController < ResourcesController
  layout 'fluid'

  def new
    render :new, locals: { form: form, report_class: report_class, report_type: params[:report_type] }
  end

  def create
    if report_class.form_class.nil? || form.valid?
      report = report_class.create! author: current_user, form: form.nil? ? {} : form.as_json.except(*%w[validation_context errors])
      redirect_to report_path(report)
    else
      new
    end
  end

  def index
    if controller_name == 'reports'
      render locals: { paginated_records: paginate(records) }, layout: 'application'
    else
      redirect_to reports_path
    end
  end

  def show
    report = Report.find params[:id]
    respond_to do |format|
      format.xlsx do
        if report.file.present?
          redirect_to url_for(report.file)
        else
          response.headers['Content-Disposition'] = "attachment; filename=\"#{report.type}-#{report.id}.xlsx\""
          render report.type.underscore, locals: { report: report }
        end
      end
      format.html do
        render locals: { report: report }
      end
    end
  end

  private

  def report_class
    (params[:report_type] || params.dig(:form, :report_type)).constantize
  end

  def form
    @form ||= report_class.form_class.new params.fetch(:form, {}).permit! if report_class.form_class.present?
  end

  def model_class
    Report
  end
end

app/helpers/reports_helper.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module ReportsHelper
end

app/views/reports/_adjustments_report.slim
- paginated_records = results[:records].page(params[:page]).per(params[:per])
- if paginated_records.total_count > 0
  div.mb-2
    = t 'application.index.total_records', count: paginated_records.total_count
  = render 'table', items: paginated_records.decorate if paginated_records.count.positive?
  = paginate paginated_records
- else
  div= t 'application.index.no_records'

app/views/reports/_bots_balance_report.slim
h1= t '.bots_balances'
hr

table.table.table-striped.table-narrow.table-bordered
  tbody
    tr
      th align='left' style='white-space: nowrap' Total
      - results['dates'].each do |date|
        th align='left' style='white-space: nowrap'
          - total_usd_amount = results['totals'][date]
          = number_to_currency(total_usd_amount, precision: 2, format: "%u%n", unit: '$', strip_insignificant_zeros: true)

    - results['currencies'].each do |currency|
      tr
        th align='left' style='white-space: nowrap' = currency
        - results['dates'].each do |date|
          td align='left' style='white-space: nowrap'
            - amount = results['records'][date][currency]['amount']
            = number_with_delimiter(amount, precision: 2, strip_insignificant_zeros: true)
    tr
      th
      - results['dates'].each do |date|
        - date = Time.parse(date)
        th align='left' style='white-space: nowrap'
          = l(date, format: :long)

br

table.table.table-striped.table-narrow.table-bordered
  tbody
    tr
      th colspan=3 Bots
    tr
      th ID
      th UID
      th Email
    - Member.bots.each do |member|
      tr
        td = member.id
        td = member.uid
        td = member.email

app/views/reports/_frame_result.slim
tr
  th= header
  - currencies.each do |currency|
    td.text-right
      - if table.nil? || table[currency].nil?
        = middot
      - else
        = format_money table[currency].to_d, currency

app/views/reports/_member_makers_trades_form.slim
= simple_form_for form, as: :form, url: reports_path do |f|
  = f.input :report_type, as: :hidden, input_html: { value: report_type }
  .row
    .col-md-4
      = f.input :market_id, collection: Market.ordered.pluck(:symbol), require: true, include_blank: 'All'
  = render 'time_range_fields', form: f

  = f.button :submit, class: 'btn btn-primary'

app/views/reports/_member_orders_form.slim
= render 'time_range_form', form: form, report_type: report_type do |f|
  .row
    .col-md-4
      .mb-2
        - if form.member.present?
          p= t '.member'
          = render 'member_brief', member: form.member
        - else
          = link_to t('.select_member'), members_path

app/views/reports/_member_records.slim
= render 'member_brief', member: member
- if paginated_records.total_count > 0
  div.mb-2
    = t 'application.index.total_records', count: paginated_records.total_count
  = render 'table', items: paginated_records.decorate if paginated_records.count.positive?
  = paginate paginated_records
- else
  div= t 'application.index.no_records'

app/views/reports/_member_records_form.slim
= render 'time_range_form', form: form, report_type: report_type do |f|
  .row
    .col-md-4
      .mb-2
        = f.input :member, as: :selectize, input_html: { data: { 'search-url' => members_path, preload: 10, value: form.member_id.try(:email) } }, required: true, multi: false

app/views/reports/_member_takers_trades_form.slim
= simple_form_for form, as: :form, url: reports_path do |f|
  = f.input :report_type, as: :hidden, input_html: { value: report_type }
  .row
    .col-md-4
      = f.input :market_id, collection: Market.ordered.pluck(:symbol), require: true, include_blank: 'All'
  .row
    .col-md-4
      = f.input :only_quick_exchange, as: :boolean
  = render 'time_range_fields', form: f

  = f.button :submit, class: 'btn btn-primary'

app/views/reports/_member_trades_report.slim
= render 'member_records', member: results[:member], paginated_records: results[:records].page(params[:page]).per(params[:per])

app/views/reports/_order_book_limits_form.slim
= render 'time_range_form', form: form, report_type: report_type do |f|
  .row
    .col-md-4
      = f.input :market_id, collection: Market.ordered, require: true, include_blank: false
    .col-md-4
      = f.input :min_order_amount, as: :numeric
    .col-md-4
      = f.input :min_trade_amount, as: :numeric

app/views/reports/_order_book_limits_report.slim
h1= Market.find_by(symbol: results[:market][:symbol]).to_s if results[:market].present?
.row
  .col-md-4
    h2= t '.top_orders_count'
    table.table.table-striped.table-narrow.table-bordered
      thead.thead-dark
        tr
          th= t '.rank'
          th= t '.member'
          th.text-right= t '.orders_count'
      tbody
        - results[:orders].each_with_index do |row, index|
          tr
            th= index + 1
            td= render 'member_brief', member: Member.find(row.first)
            td.text-right= row.second
  .col-md-4
    h2= t '.top_sellers'
    = render 'top_trades', trades: results[:sellers]
  .col-md-4
    h2= t '.top_buyers'
    = render 'top_trades', trades: results[:buyers]

h2= t '.top_volumed_orders'

.row
  - results[:top_orders].each_pair do |currency_id, data|
    - if data.present?
      .col-md-4
        h4= format_currency currency_id
        table.table.table-striped.table-narrow.table-bordered
          thead.thead-dark
            tr
              th= t '.rank'
              th= t '.member'
              th.text-right= t '.total_volume'
          tbody
            - data.each_with_index do |row, index|
              tr
                th= index + 1
                td= render 'member_brief', member: Member.find(row.first)
                td.text-right= format_money row.second, currency_id

app/views/reports/_orders_balance_report.slim
h1= t '.orders_balance'
hr
h2= t '.markets'
table.table.table-striped.table-narrow.table-bordered
  thead.thead-dark
    tr
      th= t '.market'
      th= t '.base'
      th= t '.quote'
  tbody
    - results[:markets].each_pair do |market_id, data|
      - market = Market.find_by(symbol: market_id)
      tr
        th= market.to_s
        td= format_money data[:volume], market.base_unit
        td= format_money data[:volume_price], market.quote_unit
h2= t '.currencies'
table.table.table-striped.table-narrow.table-bordered
  thead.thead-dark
    tr
      th= t '.currency'
      th= t '.amount'
  tbody
    - results[:currencies].each_pair do |currency_id, amount|
      tr
        th= format_currency currency_id
        td= format_money amount, currency_id

app/views/reports/_time_range_fields.slim
.row
  .col-md-4
    = form.input :time_from, input_html: { class: 'datetimepicker' }
  .col-md-4
    = form.input :time_to, input_html: { class: 'datetimepicker' }

app/views/reports/_top_trades.slim
table.table.table-striped.table-narrow.table-bordered
  thead.thead-dark
    tr
      th= t '.rank'
      th= t '.member'
      th.text-right= t '.trades_count'
  tbody
    - trades.each_with_index do |row, index|
      tr
        th= index + 1
        td= render 'member_brief', member: Member.find(row.first)
        td.text-right= row.second