config/routes.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  default_url_options Settings.default_url_options.symbolize_keys

  mount Sidekiq::Web => '/sidekiq'
  root to: 'dashboard#index'
  resources :reports
  resources :withdraws
  resources :deposits
  resources :transactions
  resources :accounts
  resources :trades
  resources :markets
  resources :orders
  resources :members
  resources :adjustments
  resources :internal_transfers
  resources :transfers
  resources :whaler_transfers
  resources :member_transfers
  resources :service_withdraws, only: %i[index show]
  resources :service_invoices, only: %i[index show]
  resources :service_transactions, only: %i[index show]
  resources :wallets, only: %i[index show]
  resources :bitzlato_wallets, only: %i[index show]
  resources :payment_addresses, only: %i[index show]
  resources :currencies, only: %i[index show]
  resources :blockchains, only: %i[index show]
  resources :block_numbers, only: %i[index show]
  namespace :operations do
    resources :liabilities
    resources :accounts
    resources :assets
    resources :expenses
    resources :revenues
  end
end

app/models/member.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

class Member < PeatioRecord
  BOT_UIDS = ENV.fetch('STATS_EXCLUDE_MEMBER_UIDS').split(',')
  DEEP_STONER_BOT_ID = ENV.fetch('DEEP_STONER_BOT_ID', 7)
  BARGAINER_BOT_ID = ENV.fetch('BARGAINER_BOT_ID', 6)

  has_many :orders
  has_many :accounts
  # has_many :stats_member_pnl
  has_many :payment_addresses
  has_many :withdraws, -> { order(id: :desc) }
  has_many :deposits, -> { order(id: :desc) }
  has_many :beneficiaries, -> { order(id: :desc) }
  has_many :operations_revenues, class_name: 'Operations::Revenue'
  has_many :operations_liabilities, class_name: 'Operations::Liability'

  scope :enabled, -> { where(state: 'active') }

  def trades
    Trade.by_member(id)
  end

  def self.bots
    Member.where(uid: BOT_UIDS)
  end

  def self.bots_total_balances
    bots.joins(:accounts => :currency)
        .where(currencies: { merged_token_id: nil })
        .group(:currency_id).sum('balance + locked')
  end

  def to_s
    uid
  end

  def title
    email
  end

  def get_account(model_or_id_or_code)
    case model_or_id_or_code
    when String, Symbol
      accounts.find_by(currency_id: model_or_id_or_code)
    when Currency
      accounts.find_by(currency: model_or_id_or_code)
    else
      raise "Unknown type #{model_or_id_or_code}"
    end
  end

  def balance_for(currency:, kind:)
    account_code = Operations::Account.find_by(
      type: :liability,
      kind: kind,
      currency_type: currency.type
    ).code
    liabilities = Operations::Liability.where(member_id: id, currency: currency, code: account_code)
    liabilities.sum('credit - debit')
  end
end

app/controllers/members_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

class MembersController < ResourcesController
  layout 'fluid'

  def show
    render locals: { member: Member.find(params[:id]) }
  end

  private

  def index_form
    'members_form'
  end
end

app/views/members/_members_form.slim
= render 'time_form' do |f|
  .row
    .col-md-6
      = f.input :email_or_uid_cont, as: :string

app/views/members/show.slim
.py-3= back_link root_url
.row
  .col-md-3
    h1= Member.model_name.human + ' #' + member.uid
    = render 'member_brief', member: member
  .col-md-3
    ul
      li= link_to title_with_count(Order.model_name.human_plural, member.orders.count), orders_path(q: { member_id_eq: member })
      li= link_to title_with_count(Trade.model_name.human_plural, member.trades.count), trades_path(q: { maker_id_or_taker_id_eq: member })
      li= link_to title_with_count(Deposit.model_name.human_plural, member.deposits.count), deposits_path(q: { member_id_eq: member })
      li= link_to title_with_count(Withdraw.model_name.human_plural, member.withdraws.count), withdraws_path(q: { member_id_eq: member })
      li= link_to title_with_count(PaymentAddress.model_name.human_plural, member.payment_addresses.count), payment_addresses_path(q: { member_id_eq: member })
  .col-md-3
    h3= t '.reports'
    ul
      - [MemberOrdersReport, MemberTradesReport, MemberWdReport].each do |report_class|
        li= link_to report_class.model_name.human, new_report_path(report_type: report_class, form: { member_id: member.id })
  .col-md-3
    h3= Beneficiary.model_name.human_plural
    ul
      - member.beneficiaries.each do |beneficiary|
        li= beneficiary.to_s

hr
h2= t '.accounts'
= render 'table', items: member.accounts.order(:currency_id), columns: AccountDecorator.table_columns + [:estimated_amount]
hr